server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: micro1
        uri: http://microservice1:8080/
        predicates:
        - Path=/micro1/**
      - id: micro2
        uri: http://microservicio2:8080/
        predicates:
        - Path=/micro2/**